<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141213150847 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE kaystrobach_documents_domain_model_folder_folders_join");
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_folder ADD parentfolder VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_folder ADD CONSTRAINT FK_31C78E01AAAB71F2 FOREIGN KEY (parentfolder) REFERENCES kaystrobach_documents_domain_model_folder (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_31C78E01AAAB71F2 ON kaystrobach_documents_domain_model_folder (parentfolder)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE kaystrobach_documents_domain_model_folder_folders_join (documents_folder VARCHAR(40) NOT NULL, PRIMARY KEY(documents_folder)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_folder_folders_join ADD CONSTRAINT FK_6976C16B1F273F8B FOREIGN KEY (documents_folder) REFERENCES kaystrobach_documents_domain_model_folder (persistence_object_identifier)");
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_folder DROP FOREIGN KEY FK_31C78E01AAAB71F2");
		$this->addSql("DROP INDEX IDX_31C78E01AAAB71F2 ON kaystrobach_documents_domain_model_folder");
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_folder DROP parentfolder");
	}
}