<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150111190320 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("DROP TABLE kaystrobach_documents_domain_model_folder_files_join");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE kaystrobach_documents_domain_model_folder_files_join (documents_folder VARCHAR(40) NOT NULL, documents_file VARCHAR(40) NOT NULL, INDEX IDX_6061F6DE1F273F8B (documents_folder), INDEX IDX_6061F6DEC875F534 (documents_file), PRIMARY KEY(documents_folder, documents_file)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_folder_files_join ADD CONSTRAINT FK_6061F6DE1F273F8B FOREIGN KEY (documents_folder) REFERENCES kaystrobach_documents_domain_model_folder (persistence_object_identifier)");
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_folder_files_join ADD CONSTRAINT FK_6061F6DEC875F534 FOREIGN KEY (documents_file) REFERENCES kaystrobach_documents_domain_model_file (persistence_object_identifier)");
	}
}
