<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141213160336 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_file ADD parentfolder VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_file ADD CONSTRAINT FK_AA29A1C2AAAB71F2 FOREIGN KEY (parentfolder) REFERENCES kaystrobach_documents_domain_model_folder (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_AA29A1C2AAAB71F2 ON kaystrobach_documents_domain_model_file (parentfolder)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_file DROP FOREIGN KEY FK_AA29A1C2AAAB71F2");
		$this->addSql("DROP INDEX IDX_AA29A1C2AAAB71F2 ON kaystrobach_documents_domain_model_file");
		$this->addSql("ALTER TABLE kaystrobach_documents_domain_model_file DROP parentfolder");
	}
}